language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bhushan2005/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true bhushan2005/docker-react npm run test
